### ISSUE TITLE
Typecho Theme Material Not Found.

### ISSUE THREAD

**Issue by nitu2003** [hifocus/get#25]
It seems that the redirecting link was unavailable.

`https://onedrive.idawnlight.com/Material/Material-3.4.0.zip`

**Comment by hifocus** [comment]
Sorry I just noticed this. I will see if there is any resolution.

**Comment by hifocus** [comment]
Yeah let's host the file ourselves, as the theme didn't have any new releases in years' time.
`https://app.qrcdn.com/dlc/Material-3.4.0.zip`

I would notify the responsible party @idawnlight to see if he can fix the issue himself and we can reuse his link as he is the (co)author of the theme.

Will be switching the download links now.

**Comment by idawnlight** [comment]
You can get the release simply from GitHub like `https://github.com/idawnlight/typecho-theme-material/releases/download/3.4.0/Material-3.4.0.zip`.

But anyhow, there is no further maintenance plan for this project, so it is safe to just remove the entry. The current user may still get notified of new releases of bug fixes, but I won’t recommend any new user to choose this theme.

Thank you for your attention to this project.

**Comment by hifocus** [comment]
> You can get the release simply from GitHub like `https://github.com/idawnlight/typecho-theme-material/releases/download/3.4.0/Material-3.4.0.zip`.
> 
> 
> 
> But anyhow, there is no further maintenance plan for this project, so it is safe to just remove the entry. The current user may still get notified of new releases of bug fixes, but I won’t recommend any new user to choose this theme.
> 
> 
> 
> Thank you for your attention to this project.

Initially when developing this project there is little consideration on how to expand the list of 'supported apps'. Say, 'WordPress-latest.zip' should be supported, but should its themes and similars be supported.

There is a plan to rewrite and reconstruct this project, and the new project will be named ADL (for now), but there is no exact timeframe to say when to start the development etc.

There will be some very good considerations on the new project, and deprecated themes may still be considered and contained due to their uniqueness.

Anyway thank you for your support.
